<a href="https://colab.research.google.com/github/Jagadeeshkavuri1/ML_assignment/blob/main/assian.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1.arithmetic operations on NumPy arrays


In [69]:
import numpy as k
a=k.array([5,6,7,8])
b=k.array([1,3,2,2])
print("array_1",a)
print("array_2",b)
print("addition of two matrix is ",a+b)
print("using add function",k.add(a,b))
print("------------------------------------------")
print("subtraction of two matrix is ",a-b)
print("using sub function",k.subtract(a,b))
print("------------------------------------------")
print("multiplication of two matrix is ",a*b)
print("using multiply function",k.multiply(a,b))
print("------------------------------------------")
print("division of two matrix is ",a/b)
print("using div function",k.divide(a,b))
print("------------------------------------------")
print("modulo of two matrix is ",a%b)
print("using modulo function",k.mod(a,b))
print("------------------------------------------")
print("power  of two matrix is ",a**b)
print("using power function",k.power(a,b))






array_1 [5 6 7 8]
array_2 [1 3 2 2]
addition of two matrix is  [ 6  9  9 10]
using add function [ 6  9  9 10]
------------------------------------------
subtraction of two matrix is  [4 3 5 6]
using sub function [4 3 5 6]
------------------------------------------
multiplication of two matrix is  [ 5 18 14 16]
using multiply function [ 5 18 14 16]
------------------------------------------
division of two matrix is  [5.  2.  3.5 4. ]
using div function [5.  2.  3.5 4. ]
------------------------------------------
modulo of two matrix is  [0 0 1 0]
using modulo function [0 0 1 0]
------------------------------------------
power  of two matrix is  [  5 216  49  64]
using power function [  5 216  49  64]


#3.NumPy array of integers from 10 to 50 with a step size of 5.


In [29]:
import numpy as ka
a1=ka.arange(10,50,5)
print(a1)


[10 15 20 25 30 35 40 45]


#4.Reshape the array into a 2x4 matrix

In [30]:
import numpy as kb
print("before reshape the array")
b1=kb.arange(10,50,5)
print(b1)
print("------------------------------------------")
print("after reshape the array")
a2=kb.arange(10,50,5).reshape(2,4)
print(a2)


before reshape the array
[10 15 20 25 30 35 40 45]
------------------------------------------
after reshape the array
[[10 15 20 25]
 [30 35 40 45]]


#5.
##• Extract the sub-matrix containing the last two rows and first two columns

In [37]:
import numpy as p
arr = p.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]).reshape(3,3)
print("before extracting\n",arr)
print("Extract last two rows and first two columns")
a3=arr[1:,:2]
print(a3)


before extracting
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Extract last two rows and first two columns
[[4 5]
 [7 8]]


##• Replace all elements greater than 4 with 0

In [38]:
print("before replace\n",a3)
print("------------------------------------------")
print("after replace all elements greater than 4 with 0 ")
a3[a3>4]=0
print(a3)



before replace
 [[4 5]
 [7 8]]
------------------------------------------
after replace all elements greater than 4 with 0 
[[4 0]
 [0 0]]


#6.Create two 1D arrays and Perform element-wise addition, multiplication, and division.

In [40]:
import numpy as g
c = g.array([4, 15, 12])
d = g.array([2, 5, 6])
print("array_1 : ",c,"\n array_2 : ",d)
print("addtiton is ",c+d)
print("multiplication ",c*d)
print("division is ",c/d)


array_1 :  [ 4 15 12] 
 array_2 :  [2 5 6]
addtiton is  [ 6 20 18]
multiplication  [ 8 75 72]
division is  [2. 3. 2.]


#7. Create a random NumPy array of size (4, 4). Compute:  
##• Mean of each column.
##• Maximum value of the entire array.
##• Sum of all elements.

In [56]:
import numpy as np
r_array = np.random.randint(1, 101, size=(4, 4))
print("the random array is\n",r_array)
print("------------------------------------------")
print("mean of the each column\n",np.mean(r_array,axis=0))
print("------------------------------------------")
print("Maximum value of the entire array\n",np.max(r_array))
print("------------------------------------------")
print("Sum of all elements",np.sum(r_array))




the random array is
 [[47 51 43 15]
 [32 89 46 54]
 [33 81  3  8]
 [78 70  4 11]]
------------------------------------------
mean of the each column
 [47.5  72.75 24.   22.  ]
------------------------------------------
Maximum value of the entire array
 89
------------------------------------------
Sum of all elements 665


#8.Given the array and add 10 to each element and multiply the result by 2.

In [59]:
arr1 = np.array([1, 2, 3, 4])
result = (arr1 + 10) * 2
print("Original Array:", arr1)
print("Result after adding 10 and multiplying by 2:", result)


Original Array: [1 2 3 4]
Result after adding 10 and multiplying by 2: [22 24 26 28]


#9.Perform advanced slicing and indexing on a 3D array. Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from 1 to 10

In [60]:
arr2 = np.random.randint(1, 101, size=(3, 4, 5))
print("Original Array:\n", arr2)

Original Array:
 [[[69 94 58 34 67]
  [99 34 46 49 35]
  [12  8 61 86 16]
  [50 94 32 23 29]]

 [[37 72 86  5 81]
  [78 85 60 29 91]
  [73 41 49 71 79]
  [56 84 28 19 13]]

 [[84 42 76 41  2]
  [ 4 21 55 54 58]
  [59 57 23 10 75]
  [70  7  8 89 83]]]


##• Extract the second "layer" (i.e., the second 2D array) in the first dimension.
##• Extract the first two rows and the last three columns from each "layer."
##• Replace all elements divisible by 3 with -1.

In [61]:
#1. Extract the second "layer" in the first dimension
second_layer = arr2[1, :, :]
print("\nSecond Layer:\n", second_layer)

# 2. Extract the first two rows and the last three columns from each "layer"
sub_array = arr2[:, :2, -3:]
print("\nFirst two rows and last three columns from each layer:\n", sub_array)

# 3. Replace all elements divisible by 3 with -1
arr2[arr2 % 3 == 0] = -1
print("\nArray after replacing elements divisible by 3 with -1:\n", arr2)



Second Layer:
 [[37 72 86  5 81]
 [78 85 60 29 91]
 [73 41 49 71 79]
 [56 84 28 19 13]]

First two rows and last three columns from each layer:
 [[[58 34 67]
  [46 49 35]]

 [[86  5 81]
  [60 29 91]]

 [[76 41  2]
  [55 54 58]]]

Array after replacing elements divisible by 3 with -1:
 [[[-1 94 58 34 67]
  [-1 34 46 49 35]
  [-1  8 61 86 16]
  [50 94 32 23 29]]

 [[37 -1 86  5 -1]
  [-1 85 -1 29 91]
  [73 41 49 71 79]
  [56 -1 28 19 13]]

 [[-1 -1 76 41  2]
  [ 4 -1 55 -1 58]
  [59 -1 23 10 -1]
  [70  7  8 89 83]]]


#10. Work with broadcasting and advanced operations in NumPy. Create a NumPy array arr of shape (3, 3) with random integers between  1 and 20.
##• Subtract the mean of each row from its respective elements (row-wise normalization).
##• Create a new array by squaring all the elements in arr.
##• Find the indices of the top 3 maximum values in the entire array

In [67]:
arr4 = np.random.randint(1, 21, size=(3, 3))
print("Original Array (arr4):\n", arr4)
row_means = np.mean(arr4, axis=1, keepdims=True)
normalized_arr = arr4 - row_means
print("\nRow-wise Normalized Array (mean subtracted):\n", normalized_arr)

# 3. Create a new array by squaring all the elements in arr4
squared_arr = np.square(arr4)
print("\nArray with squared elements:\n", squared_arr)

# 4. Find the indices of the top 3 maximum values in the entire array
top_3_indices = np.unravel_index(np.argsort(arr4, axis=None)[-3:], arr4.shape)
print("\nIndices of the top 3 maximum values:", top_3_indices)

Original Array (arr4):
 [[16  8  8]
 [ 8 15 18]
 [18 19 19]]

Row-wise Normalized Array (mean subtracted):
 [[ 5.33333333 -2.66666667 -2.66666667]
 [-5.66666667  1.33333333  4.33333333]
 [-0.66666667  0.33333333  0.33333333]]

Array with squared elements:
 [[256  64  64]
 [ 64 225 324]
 [324 361 361]]

Indices of the top 3 maximum values: (array([2, 2, 2]), array([0, 1, 2]))


#2. Write a script to compute the mean and standard deviation of a NumPy array.