<a href="https://colab.research.google.com/github/Jagadeeshkavuri1/ML_assignment/blob/main/assian.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1)arithmetic operations on NumPy arrays


In [25]:
import numpy as k
a=k.array([5,6,7,8])
b=k.array([1,3,2,2])
print("array_1",a)
print("array_2",b)
print("addition of two matrix is ",a+b)
print("using add function",k.add(a,b))
print("------------------------------------------")
print("subtraction of two matrix is ",a-b)
print("using sub function",k.subtract(a,b))
print("------------------------------------------")
print("multiplication of two matrix is ",a*b)
print("using multiply function",k.multiply(a,b))
print("------------------------------------------")
print("division of two matrix is ",a/b)
print("using div function",k.divide(a,b))
print("------------------------------------------")
print("modulo of two matrix is ",a%b)
print("using modulo function",k.mod(a,b))
print("------------------------------------------")
print("power  of two matrix is ",a**b)
print("using power function",k.power(a,b))






array_1 [5 6 7 8]
array_2 [1 3 2 2]
addition of two matrix is  [ 6  9  9 10]
using add function [ 6  9  9 10]
------------------------------------------
subtraction of two matrix is  [4 3 5 6]
using sub function [4 3 5 6]
------------------------------------------
multiplication of two matrix is  [ 5 18 14 16]
using multiply function [ 5 18 14 16]
------------------------------------------
division of two matrix is  [5.  2.  3.5 4. ]
using div function [5.  2.  3.5 4. ]
------------------------------------------
modulo of two matrix is  [0 0 1 0]
using modulo function [0 0 1 0]
------------------------------------------
power  of two matrix is  [  5 216  49  64]
using power function [  5 216  49  64]


#2)Write a script to compute the mean and standard deviation of a NumPy array.

In [26]:
ke=([1,2,3,4,5])
print("mean of the array is ",k.mean(ke))
print("standard devation is ",k.std(ke))

mean of the array is  3.0
standard devation is  1.4142135623730951


#3)NumPy array of integers from 10 to 50 with a step size of 5.


In [ ]:
import numpy as ka
a1=ka.arange(10,51,5)
print(a1)

[10 15 20 25 30 35 40 45 50]


#4)Reshape the array into a 2x4 matrix

In [ ]:
import numpy as kb
print("before reshape the array")
b1=kb.arange(10,50,5)
print(b1)
print("------------------------------------------")
print("after reshape the array")
a2=kb.arange(10,50,5).reshape(2,4)
print(a2)


before reshape the array
[10 15 20 25 30 35 40 45]
------------------------------------------
after reshape the array
[[10 15 20 25]
 [30 35 40 45]]


#5)


##(i)Extract the sub-matrix containing the last two rows and first two columns

In [ ]:
import numpy as p
arr = p.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]).reshape(3,3)
print("before extracting\n",arr)
print("Extract last two rows and first two columns")
a3=arr[1:,:2]
print(a3)


before extracting
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Extract last two rows and first two columns
[[4 5]
 [7 8]]


##(ii)Replace all elements greater than 4 with 0

In [ ]:
print("before replace\n",a3)
print("------------------------------------------")
print("after replace all elements greater than 4 with 0 ")
a3[a3>4]=0
print(a3)



before replace
 [[4 5]
 [7 8]]
------------------------------------------
after replace all elements greater than 4 with 0 
[[4 0]
 [0 0]]


#6)Create two 1D arrays and Perform element-wise addition, multiplication, and division.

In [ ]:
import numpy as g
c = g.array([4, 15, 12])
d = g.array([2, 5, 6])
print("array_1 : ",c,"\n array_2 : ",d)
print("addtiton is ",c+d)
print("multiplication ",c*d)
print("division is ",c/d)


array_1 :  [ 4 15 12] 
 array_2 :  [2 5 6]
addtiton is  [ 6 20 18]
multiplication  [ 8 75 72]
division is  [2. 3. 2.]


#7. Create a random NumPy array of size (4, 4). Compute:  

In [27]:
import numpy as np
r_array = np.random.randint(1, 101, size=(4, 4))
print("the random array is\n",r_array)

the random array is
 [[53 53 58 92]
 [89 42 16 37]
 [57 85 32 32]
 [15 85 83 60]]


##(i)Mean of each column.


In [30]:
print("mean of the each column\n",np.mean(r_array,axis=0))

mean of the each column
 [53.5  66.25 47.25 55.25]


##(ii)Maximum value of the entire array.

In [29]:
print("Maximum value of the entire array\n",np.max(r_array))


Maximum value of the entire array
 92


##(iii) Sum of all elements.

In [28]:
print("sum of all elements in array is",np.sum(r_array))

sum of all elements in array is 889


#8)Given the array and add 10 to each element and multiply the result by 2.

In [ ]:
arr1 = np.array([1, 2, 3, 4])
result = (arr1 + 10) * 2
print("Original Array:", arr1)
print("Result after adding 10 and multiplying by 2:", result)


Original Array: [1 2 3 4]
Result after adding 10 and multiplying by 2: [22 24 26 28]


#9.Perform advanced slicing and indexing on a 3D array. Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from 1 to 10

In [31]:
arr2 = np.random.randint(1, 101, size=(3, 4, 5))
print("Original Array:\n", arr2)

Original Array:
 [[[ 39  89 100  11  66]
  [ 53  74  79   2  77]
  [ 80  69  93  96  86]
  [ 41  25  51  67  16]]

 [[ 77  48  94  51  72]
  [ 77  21  49  52  44]
  [ 22  82  82  94  41]
  [ 23  75  91  52  84]]

 [[ 74  89   4  92  74]
  [ 80   3  75  29  74]
  [ 11  81  69  15  87]
  [ 65  56   4  51  27]]]


##(i)Extract the second "layer" (i.e., the second 2D array) in the first dimension.


In [32]:
second_layer = arr2[1, :, :]
print("\nSecond Layer:\n", second_layer)


Second Layer:
 [[77 48 94 51 72]
 [77 21 49 52 44]
 [22 82 82 94 41]
 [23 75 91 52 84]]


##(ii)Extract the first two rows and the last three columns from each "layer."


In [33]:
sub_array = arr2[:, :2, -3:]
print("\nFirst two rows and last three columns from each layer:\n", sub_array)


First two rows and last three columns from each layer:
 [[[100  11  66]
  [ 79   2  77]]

 [[ 94  51  72]
  [ 49  52  44]]

 [[  4  92  74]
  [ 75  29  74]]]


##(iii)Replace all elements divisible by 3 with -1.

In [34]:
arr2[arr2 % 3 == 0] = -1
print("\nArray after replacing elements divisible by 3 with -1:\n", arr2)


Array after replacing elements divisible by 3 with -1:
 [[[ -1  89 100  11  -1]
  [ 53  74  79   2  77]
  [ 80  -1  -1  -1  86]
  [ 41  25  -1  67  16]]

 [[ 77  -1  94  -1  -1]
  [ 77  -1  49  52  44]
  [ 22  82  82  94  41]
  [ 23  -1  91  52  -1]]

 [[ 74  89   4  92  74]
  [ 80  -1  -1  29  74]
  [ 11  -1  -1  -1  -1]
  [ 65  56   4  -1  -1]]]


#10. Work with broadcasting and advanced operations in NumPy. Create a NumPy array arr of shape (3, 3) with random integers between  1 and 20.


In [43]:
arr4 = np.random.randint(1, 21, size=(3, 3))
print("Original Array (arr4):\n", arr4)

Original Array (arr4):
 [[ 9 19 12]
 [10 15 19]
 [17 18  5]]


####(i)Subtract the mean of each row from its respective elements (row-wise normalization).


In [42]:
print("Original Array (arr4):\n", arr4)
row_means = np.mean(arr4, axis=1, keepdims=True)
normalized_arr = arr4 - row_means
print("\nRow-wise Normalized Array (mean subtracted):\n", normalized_arr)

Original Array (arr4):
 [[18 16 17]
 [16  3  1]
 [ 1 13 10]]

Row-wise Normalized Array (mean subtracted):
 [[ 1.         -1.          0.        ]
 [ 9.33333333 -3.66666667 -5.66666667]
 [-7.          5.          2.        ]]


##(ii) Create a new array by squaring all the elements in arr.


In [41]:
print("Original Array (arr4):\n", arr4)
squared_arr = np.square(arr4)
print("\nArray with squared elements:\n", squared_arr)

Original Array (arr4):
 [[18 16 17]
 [16  3  1]
 [ 1 13 10]]

Array with squared elements:
 [[324 256 289]
 [256   9   1]
 [  1 169 100]]


##(iii)Find the indices of the top 3 maximum values in the entire array

In [45]:
print("Original Array (arr4):\n", arr4)
d1=arr4.flatten()
s2=np.argsort(d1)[6:]
r2=s2//arr4.shape[1]
g2=s2%arr4.shape[1]
t3=list(zip(r2,g2))
print("top 3 maximum values indicies :\n",t3)

Original Array (arr4):
 [[ 9 19 12]
 [10 15 19]
 [17 18  5]]
top 3 maximum values indicies :
 [(2, 1), (0, 1), (1, 2)]
